name: finjoy_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.5.4
  hive: ^2.2.3
  path_provider: ^2.1.1
  pinput: ^3.0.1
  intl: ^0.18.1
  image_picker: ^0.8.5+3
  carousel_slider: ^4.2.1
  scoped_model: ^2.0.0
  dotted_line: ^3.2.2
  dotted_border: ^2.0.0+3
  lottie: ^2.7.0
  syncfusion_flutter_charts: ^23.1.42
  pattern_formatter: ^3.0.0
  dropdown_search: ^5.0.6
  platform: ^3.1.3
  flutter_bloc: ^8.1.1
  http: ^1.1.0
  connectivity: ^3.0.6
#  internet_connection_checker: ^0.0.1+3
  rxdart: ^0.27.7
  mask_text_input_formatter: ^2.6.0
  google_sign_in: ^6.1.6
  video_player: ^2.8.1
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  internet_connection_checker:
  get:
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_html: ^3.0.0-beta.2
  youtube_player_flutter: ^8.1.2
  pdf_thumbnail:
  url_launcher: ^6.2.2
  fluttertoast: ^8.2.4
  widgets_to_image: ^0.0.2
  webview_flutter: ^3.0.0
  qr_flutter: ^4.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  flutter_local_notifications: ^9.6.0
  onesignal_flutter: ^5.0.4
  custom_date_range_picker: ^1.0.10
  build_context_provider: ^1.1.0
  audioplayers: ^5.2.1
  mixpanel_flutter: ^2.2.0
  flutter_dash: ^1.0.0
  flutter_pdfview: ^1.3.2
#  multi_dropdown: ^2.1.2
  geolocator: ^10.1.0
  local_auth: ^2.1.7
  page_transition: ^2.0.5


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/app_sound/
    - assets/images/onboarding/
    - assets/images/select language/
    - assets/images/login/
    - assets/images/otp/
    - assets/images/forgot m pin/
    - assets/images/sign up/
    - assets/images/profile/
    - assets/images/kyc sucess/
    - assets/images/home/
    - assets/images/bottombar/
    - assets/images/sell & earn/
    - assets/images/credit card/
    - assets/images/new bottombar/
    - assets/images/drawer/
    - assets/images/finjoy briefcase/
    - assets/images/my customer/
    - assets/images/loans/
    - assets/images/investment/
    - assets/images/marketing/
    - assets/images/training/
    - assets/images/notification/
    - assets/images/wallet/
    - assets/images/enter m pin/
    - assets/images/website/
    - assets/images/referAndEarn/
    - assets/images/leader_board/
    - assets/images/static icons/
    - assets/images/customer/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
